<a href="https://colab.research.google.com/github/redpineK/deeplearning/blob/master/embedding3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
import numpy as np

In [10]:
model = Sequential()
embedding_layer = Embedding(input_dim=10,output_dim=4,input_length=2)
model.add(embedding_layer)
model.compile('adam','mse')
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 2, 4)              40        
                                                                 
Total params: 40
Trainable params: 40
Non-trainable params: 0
_________________________________________________________________


In [11]:
input_data = np.array([[1,2]])
pred = model.predict(input_data)
print(input_data.shape)
print(pred)

1/1 [==============================] - 0s 42ms/step
(1, 2)
[[[-0.03652147  0.00402728  0.03052224  0.01641984]
  [-0.01442857  0.0385086  -0.03639083  0.01341119]]]


In [15]:
print(input_data)
print(input_data.shape)
print(pred)
print(pred.shape)

[[1 2]]
(1, 2)
[[[-0.03652147  0.00402728  0.03052224  0.01641984]
  [-0.01442857  0.0385086  -0.03639083  0.01341119]]]
(1, 2, 4)
