<a href="https://colab.research.google.com/github/redpineK/deeplearning/blob/master/emdegging6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
import numpy as np

In [10]:
model = Sequential()
embedding_layer = Embedding(input_dim=10,output_dim=4,input_length=2)
model.add(embedding_layer)
model.compile('adam','mse')
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 2, 4)              40        
                                                                 
Total params: 40
Trainable params: 40
Non-trainable params: 0
_________________________________________________________________


In [11]:
input_data = np.array([[1,2]])
pred = model.predict(input_data)
print(input_data.shape)
print(pred)

1/1 [==============================] - 0s 42ms/step
(1, 2)
[[[-0.03652147  0.00402728  0.03052224  0.01641984]
  [-0.01442857  0.0385086  -0.03639083  0.01341119]]]


In [15]:
print(input_data)
print(input_data.shape)
print(pred)
print(pred.shape)

[[1 2]]
(1, 2)
[[[-0.03652147  0.00402728  0.03052224  0.01641984]
  [-0.01442857  0.0385086  -0.03639083  0.01341119]]]
(1, 2, 4)


In [16]:
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten,Embedding,Dense

In [17]:
# Define 10 restaurant reviews
reviews =[
          'Never coming back!',
          'horrible service',
          'rude waitress',
          'cold food',
          'horrible food!',
          'awesome',
          'awesome services!',
          'rocks',
          'poor work',
          'couldn\'t have done better'
]
#Define labels
labels = array([1,1,1,1,1,0,0,0,0,0])

In [18]:
Vocab_size = 50
encoded_reviews = [one_hot(d,Vocab_size) for d in reviews]
print(f'encoded reviews: {encoded_reviews}')

encoded reviews: [[31, 36, 26], [33, 20], [25, 24], [31, 29], [33, 29], [9], [9, 44], [22], [44, 30], [31, 7, 18, 21]]


In [19]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[31 36 26  0]
 [33 20  0  0]
 [25 24  0  0]
 [31 29  0  0]
 [33 29  0  0]
 [ 9  0  0  0]
 [ 9 44  0  0]
 [22  0  0  0]
 [44 30  0  0]
 [31  7 18 21]]


In [20]:
model = Sequential()
embedding_layer = Embedding(input_dim=Vocab_size,output_dim=8,input_length=max_length)
model.add(embedding_layer)
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 4, 8)              400       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [21]:
model.fit(padded_reviews,labels,epochs=100,verbose=0)

In [30]:
print(embedding_layer.get_weights()[0].shape)
print(embedding_layer.get_weights()[0])

(50, 8)
[[ 9.03753638e-02 -1.04301870e-01  1.18698761e-01  6.95015565e-02
  -1.25340894e-01  1.39426425e-01 -8.26701894e-02  1.56707913e-01]
 [ 3.28953192e-03 -4.45670150e-02  2.01883204e-02  2.87561528e-02
  -8.57148319e-03  3.35103609e-02 -3.79138477e-02 -2.40823515e-02]
 [-4.57929149e-02  3.75991128e-02 -2.00870279e-02 -3.18695232e-03
   1.84111856e-02 -1.67550817e-02 -1.70323960e-02 -8.05014372e-03]
 [ 2.19738744e-02 -1.21686570e-02 -8.94962624e-03  3.17842104e-02
  -2.52251029e-02  2.46567987e-02  2.73606069e-02  2.79983543e-02]
 [-1.05029456e-02  2.55553797e-03  3.16648521e-02  4.60787304e-02
   3.46557982e-02 -9.94142145e-03  1.45652033e-02 -3.24848443e-02]
 [ 3.92544977e-02 -4.65613380e-02 -3.16541567e-02 -4.42232005e-02
   3.73439677e-02  1.07254162e-02 -7.98001140e-03 -2.64505297e-03]
 [-3.20354477e-02 -1.13021508e-02  6.21206686e-03  1.47438906e-02
  -1.73926130e-02 -6.82985783e-03  4.78762873e-02 -3.49171087e-03]
 [ 1.14405558e-01 -1.12721823e-01  1.20916322e-01  1.44478679

In [24]:
padded_reviews.shape


(10, 4)

In [26]:
pred  = model.predict(padded_reviews)
print(pred)

1/1 [==============================] - 0s 49ms/step
[[0.7129587 ]
 [0.6296881 ]
 [0.6465909 ]
 [0.6440757 ]
 [0.6358964 ]
 [0.32205626]
 [0.35885975]
 [0.32690954]
 [0.34922454]
 [0.38764417]]
