<a href="https://colab.research.google.com/github/redpineK/deeplearning/blob/master/wordembedding_prractice2_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

출처 - https://wikidocs.net/32105
출처 - https://taeguu.tistory.com/69

In [9]:
import numpy as np
import tensorflow as tf

raw_inputs = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,0],
])

embedding = tf.keras.layers.Embedding(
    input_dim = 10, output_dim = 2, mask_zero = True
)

output = embedding(raw_inputs)

print(output)

tf.Tensor(
[[[ 0.02417648 -0.00098808]
  [-0.02850262 -0.04900086]
  [ 0.04472769 -0.04089211]]

 [[-0.03007719  0.01265666]
  [-0.01090667 -0.02249056]
  [ 0.03585598  0.00795426]]

 [[ 0.0054244   0.02063299]
  [ 0.00556815 -0.0335386 ]
  [ 0.02259988  0.03657872]]], shape=(3, 3, 2), dtype=float32)


In [10]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Embedding, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# train_text = "The earth is an awesome place live"
text = ["나는 밥을 먹었다", "나는 학교에 갔다", "오늘 학교에 선생님이 오셨다"]
# 단어 집합 생성
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text)
sequences = tokenizer.texts_to_sequences(text)
# 정수 인코딩
word_index = tokenizer.word_index
print("정수 인코딩 : ",sequences)
print("단어 집합 : ",word_index)

정수 인코딩 :  [[1, 3, 4], [1, 2, 5], [6, 2, 7, 8]]
단어 집합 :  {'나는': 1, '학교에': 2, '밥을': 3, '먹었다': 4, '갔다': 5, '오늘': 6, '선생님이': 7, '오셨다': 8}


In [11]:
data = pad_sequences(sequences, maxlen=4, padding='post')
print(data)
print(data.shape)

[[1 3 4 0]
 [1 2 5 0]
 [6 2 7 8]]
(3, 4)


In [12]:
embedding_dim = 100
model = Sequential()
model.add(Embedding(len(word_index) + 1, embedding_dim, input_length=4))
model.compile('rmsprop','mse')
model.summary()
print("input array: ", data.shape)
output_array = model.predict(data)
print("output array: ", output_array.shape)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 4, 100)            900       
                                                                 
Total params: 900
Trainable params: 900
Non-trainable params: 0
_________________________________________________________________
input array:  (3, 4)
1/1 [==============================] - 0s 231ms/step
output array:  (3, 4, 100)


In [15]:
type(model)
model

In [ ]:
print("첫번째 문장 embedding 결과 : ", output_array[0][0])
print("두번째 문장 embedding 결과 : ", output_array[1][0])

첫번째 문장 embedding 결과 :  [ 0.02549931  0.00573844 -0.0313284   0.02795484  0.03318924  0.02546461
 -0.04146696 -0.00453953  0.04116144  0.01345712  0.01004329  0.04576221
 -0.02661508  0.02259971  0.00019739  0.04076651  0.03691976 -0.01220553
  0.01727128  0.04675208  0.04767982  0.03141779 -0.02067733  0.01823011
 -0.02536675  0.01861408 -0.01715596 -0.03122287  0.04869511 -0.01129771
  0.0200212  -0.04884242  0.03302152 -0.04145394 -0.02602971  0.04042307
  0.0047039  -0.00766909 -0.00318252 -0.01364858  0.00625874 -0.04773426
  0.00827658  0.01779832  0.03293863 -0.02912314  0.03277463  0.01181341
 -0.01059031 -0.01498593  0.01595111 -0.02037647 -0.03093036  0.04011032
 -0.01833414 -0.03132057  0.0341225   0.02172519  0.0282363  -0.00629539
  0.00572466  0.01425943  0.03551254  0.00095893 -0.00253319 -0.01421244
  0.01046241  0.0171574   0.01787332 -0.00429909 -0.0032467   0.01614984
  0.00884765 -0.03575505 -0.03874158 -0.00590372 -0.03032322  0.02590361
 -0.04629814 -0.03590786 -0.

In [ ]:
# 1. 토큰화
tokenized_text = [['Hope', 'to', 'see', 'you', 'soon'], ['Nice', 'to', 'see', 'you', 'again']]

# 2. 각 단어에 대한 정수 인코딩
encoded_text = [[0, 1, 2, 3, 4],[5, 1, 2, 3, 6]]

# 3. 위 정수 인코딩 데이터가 아래의 임베딩 층의 입력이 된다.
vocab_size = 7
embedding_dim = 2
Embedding(vocab_size, embedding_dim, input_length=5)

In [ ]:
vocab_size = 10000
embedding_dim = 32
hidden_units = 32
# input_length = 4
model = Sequential()
model.add(Embedding(vocab_size, embedding_dim, input_length = 4))
model.add(SimpleRNN(hidden_units))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
model.summary()

Model: "sequential_16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_20 (Embedding)    (None, 4, 32)             320000    
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 322,113
Trainable params: 322,113
Non-trainable params: 0
_________________________________________________________________
